const eventsList = [
  {
    title: "Annual Fundraising Dinner",
    dateStart: "17 Feb 2023",
    dateEnd: "17 feb 2023 6:30 pm",
    timeString: "6:30 pm to 9:30 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Fundraisers",
  },
  {
    title: "Stroll By The Bay",
    dateStart: "18 Feb 2023",
    dateEnd: "18 feb 2023 10:30 am",
    timeString: "7:30 am to 10:30 am",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Stroll By The Beach",
    dateStart: "18 Feb 2023",
    dateEnd: "18 feb 2023 10:30 am",
    timeString: "7:30 am to 10:30 am",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Garden of Hope - Flower planting",
    dateStart: "19 Feb 2023",
    dateEnd: "19 Feb 2023 2:30 PM",
    timeString: "11:00AM to 2:30PM",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Stroll By The Bay",
    dateStart: "19 Feb 2023",
    dateEnd: "19 Feb 2023 10:30 AM",
    timeString: "7:00AM to 10:30AM",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Stroll By The Shore",
    dateStart: "19 Feb 2023",
    dateEnd: "19 Feb 2023 10:30 AM",
    timeString: "7:00AM to 10:30AM",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Medical Talk - Essential Caregiving Skills",
    dateStart: "21 Feb 2023",
    dateEnd: "21 feb 2023 9:00 am",
    timeString: "11:00 am",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Talks",
  },
  {
    title: "Seniors Go Digital",
    dateStart: "21 Feb 2023",
    dateEnd: "23 Feb 2023",
    timeString: "9:00 am to 10:30am",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Classes & Workshops",
  },
  {
    title: "Health Talk - Essential Nutrition",
    dateStart: "23 Feb 2023",
    dateEnd: "23 feb 2023 2:00 pm",
    timeString: "11:00 am to 2:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Talks",
  },
  {
    title: "Health Talk - Essential Exercises",
    dateStart: "25 Feb 2023",
    dateEnd: "25 feb 2023 2:00 pm",
    timeString: "11:00 am to 2:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Talks",
  },
  {
    title: "Seniors Go Kopitiam",
    dateStart: "26 Feb 2023",
    dateEnd: "26 feb 2023 2:00 pm",
    timeString: "11:00 am to 2:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Seniors Go Golden Village",
    dateStart: "28 Feb 2023",
    dateEnd: "28 feb 2023 8:00 pm",
    timeString: "8:00 pm to 11:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Community Gathering",
  },
  {
    title: "Seniors and Iphones",
    dateStart: "1 Mar 2023",
    dateEnd: "1 Mar 2023 8:00 pm",
    timeString: "8:00 pm to 11:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Classes & Workshops",
  },
  {
    title: "Seniors and Androids",
    dateStart: "2 Mar 2023",
    dateEnd: "2 Mar 2023 8:00 pm",
    timeString: "8:00 pm to 11:00 pm",
    description: "Lorem ipsum dolor sit amet",
    img: "Lorem ipsum dolor sit",
    action: "Lorem Link",
    tag: "Classes & Workshops",
  },
];

module.exports = eventsList;
